#!/bin/bash -e
if [[ ! -f "/home/spark-e16f2474-7da9-4e14-a236-ef/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-e16f2474-7da9-4e14-a236-ef/tmp/uv/uv_0.6.10_linux_arm64" "$@"
